/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.CRUDConcepto;
import Controlador.Concepto;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chris
 */
public class PanelConcepto extends javax.swing.JFrame {

    private Concepto concepto;
    private PanelProductos panelproducto;
    private boolean edicion=false;
    private CRUDConcepto conceptos;

    public PanelConcepto() {
        initComponents();
        setLocationRelativeTo(null);
        
    }
    //Construtor con parametros
    public  PanelConcepto(PanelProductos x,boolean y){
        this.panelproducto=x;
        this.edicion=y;
        initComponents();
        setLocationRelativeTo(null);
        concepto=new Concepto();
        conceptos=new CRUDConcepto();
        estado();
    }
    
    private void Limpiar() {
        //limpiando los datos del formulario
        txtid.setText("");
        txtconcepto.setText("");
    }
    
    private void estado(){
        cargaTabla();
        btnelimina.setVisible(edicion); //mostrar boton eliminar 
        btnbusca.setVisible(!edicion);
        btseleccionar.setVisible(edicion);
        txtbusca.setVisible(!edicion);
        lb1.setVisible(!edicion);
        if(!edicion){//No se esta editando
            btnacepta.setText("Agregar");
        }else{//se esta editando
            btnacepta.setText("Guardar");
        }   
    }
    
    private void cargaConcepto() {
        try {
            int fila = tb.getSelectedRow(); //Obtenemos la fila

            //Creando objeto para utilizar despues en actualizar, eliminar, seleccionar
            concepto.setId_concepto(Integer.parseInt(tb.getValueAt(fila, 0).toString()));
            concepto.setConcepto(tb.getValueAt(fila, 1).toString());

            //Cargando los datos en el formulario
            txtid.setText(String.valueOf(concepto.getId_concepto()));
            txtconcepto.setText(concepto.getConcepto());

            //se seleciona un objeto y habilitamos su edicion
            edicion = true;
            estado();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error al seleccionar de tabla: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void cargaTabla() {
        //creando el modelo de la tabla
        DefaultTableModel modelo = conceptos.lista(txtbusca.getText());
        //tamaño de las columnas
        int[] anchos = {50, 500};
        for (int i = 0; i < tb.getColumnCount(); i++) {
            tb.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
        }
        tb.setModel(modelo);
        tb.setDefaultEditor(Object.class, null); //La tabla no es editable  
    }
        
    private boolean FormularioOk() {
        boolean bandera = true;

        if (txtid.getText().isEmpty()) {
           bandera = false;
        }
        if (txtconcepto.getText().isEmpty()) {
            bandera = false;
        }
        return bandera;
    }
    
    private void cargarFormulario() {
        //variables a utilizar
        int id;
        String c;
        //obteneiendo datos del formulario
        id = Integer.parseInt(txtid.getText());
        c = txtconcepto.getText();

        //Insertando los datos en el objeto
        concepto.setId_concepto(id);
        concepto.setConcepto(c);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        txtid = new javax.swing.JTextField();
        btnacepta = new javax.swing.JButton();
        btnelimina = new javax.swing.JButton();
        btseleccionar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtconcepto = new javax.swing.JTextField();
        btnbusca = new javax.swing.JButton();
        txtbusca = new javax.swing.JTextField();
        lb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Concepto");
        setResizable(false);
        setSize(new java.awt.Dimension(600, 400));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel2.setText("Concepto");

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Concepto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb);

        txtid.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtidKeyTyped(evt);
            }
        });

        btnacepta.setBackground(new java.awt.Color(0, 153, 102));
        btnacepta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnacepta.setForeground(new java.awt.Color(255, 255, 255));
        btnacepta.setText("Agregar");
        btnacepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaceptaActionPerformed(evt);
            }
        });

        btnelimina.setBackground(new java.awt.Color(255, 102, 102));
        btnelimina.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnelimina.setForeground(new java.awt.Color(255, 255, 255));
        btnelimina.setText("Eliminar");
        btnelimina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminaMouseClicked(evt);
            }
        });

        btseleccionar.setBackground(new java.awt.Color(51, 153, 255));
        btseleccionar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btseleccionar.setForeground(new java.awt.Color(255, 255, 255));
        btseleccionar.setText("Seleccionar");
        btseleccionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btseleccionarMouseClicked(evt);
            }
        });

        btncancelar.setBackground(new java.awt.Color(102, 102, 102));
        btncancelar.setForeground(new java.awt.Color(255, 255, 255));
        btncancelar.setText("Cancelar");
        btncancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncancelarMouseClicked(evt);
            }
        });

        jLabel1.setText("ID");

        txtconcepto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconceptoKeyTyped(evt);
            }
        });

        btnbusca.setBackground(new java.awt.Color(102, 102, 102));
        btnbusca.setForeground(new java.awt.Color(255, 255, 255));
        btnbusca.setText("Buscar");
        btnbusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnbuscaMouseClicked(evt);
            }
        });

        txtbusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscaKeyTyped(evt);
            }
        });

        lb1.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(129, 129, 129)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnbusca))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(txtconcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnacepta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnelimina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbusca))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtconcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btseleccionar)
                        .addGap(18, 18, 18)
                        .addComponent(btnacepta)
                        .addGap(19, 19, 19)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnelimina)
                        .addContainerGap(57, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyTyped
        // Verificando que solo sean numeros
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;

        if (!numeros) {
            evt.consume();
        }
        //Estableciendo longitud max
        if (txtid.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtidKeyTyped

    private void btnaceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaceptaActionPerformed

        // Se presiona boton aceptar
        if (FormularioOk()) { //verificamos que no falte ningun dato
            if (!edicion) {//agregando
                cargarFormulario(); //cargamos los datos escritos en el formulario
                conceptos.Insertar(concepto); //llamamos al metodo para ingresar nuevo 
            } else {//actualizando
                int id=Integer.parseInt(txtid.getText());//id antiguo en caso de cambiarse
                cargarFormulario(); //cargando los nuevos datos
                conceptos.Actualizar(id,concepto);//envio el objeto producto a crud para actualizarlo
                edicion = false;
            }
            Limpiar();
            estado();
        }else{JOptionPane.showMessageDialog(this, "Faltan campos por llenar");}

    }//GEN-LAST:event_btnaceptaActionPerformed

    private void btseleccionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btseleccionarMouseClicked
        // Al seleccionar  
        panelproducto.setConcepto(concepto);
        this.setVisible(false);
        panelproducto.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btseleccionarMouseClicked

    private void btncancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncancelarMouseClicked
        if (edicion) {//se esta editando
            // Limpia el formulario
            edicion = false;
            estado();
            Limpiar();
        } else {//no se esta editando
            panelproducto.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btncancelarMouseClicked

    private void btneliminaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminaMouseClicked
        //Se presiona boton para eliminar
        if (JOptionPane.showConfirmDialog(this, "Se eliminará ¿Desea continuar?",
                "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            conceptos.Eliminar(concepto.getId_concepto());//envio el objeto
            edicion = false;
            estado();
            Limpiar();

        }
    }//GEN-LAST:event_btneliminaMouseClicked

    private void tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMouseClicked
        // Obtener el datocque se selecciona en la tabla
        cargaConcepto();
    }//GEN-LAST:event_tbMouseClicked

    private void btnbuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbuscaMouseClicked
        // Busca
        cargaTabla();
    }//GEN-LAST:event_btnbuscaMouseClicked

    private void txtbuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyTyped
        //Estableciendo longitud max
        if (txtid.getText().length() == 50) {
            evt.consume();
        }
    }//GEN-LAST:event_txtbuscaKeyTyped

    private void txtconceptoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconceptoKeyTyped
        // TODO add your handling code here:
        if (txtconcepto.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_txtconceptoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelConcepto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelConcepto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacepta;
    private javax.swing.JButton btnbusca;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnelimina;
    private javax.swing.JButton btseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTable tb;
    private javax.swing.JTextField txtbusca;
    private javax.swing.JTextField txtconcepto;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables
}
