/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.CRUDItems;
import Modelo.CRUDPedidos;
import Modelo.CRUDProductos;
import Controlador.Item;
import Controlador.Pedido;
import Controlador.Producto;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Chris
 */
public class PanelItem extends javax.swing.JFrame {

 
    private Producto producto;
    private Pedido pedido;
    private Item item;
    private boolean bandera; //true se esta editando, false no se esta editando
    private PanelPedidos panel;
    private CRUDProductos productos;
    private CRUDPedidos pedidos ;
    private CRUDItems items;

    /**
     * Creates new form PanelItem
     */
    public PanelItem() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void cargaproducto(int x){ //cargamos el producto
        productos = new CRUDProductos();
        //this.producto=new Producto();
        this.producto=productos.busca(x);
    }
    public void cargaPedido(int x){//cargamos el pedido
        pedidos=new CRUDPedidos();     
        this.pedido=pedidos.busca(x);
    }
    public void cargaitem(Item x){//cargamos item 
        this.item=x;
        cargaPedido(this.item.getId_pedido());
        cargaproducto(this.item.getId_producto());
    }
    public void cargabandera(boolean x){//cargamos bandera
        this.bandera=x;
    }
    public void cargaPanel(PanelPedidos x){//cargamos panel
        this.panel=x;
    }
    
    
       
    public void estado(){
        txtnombre.setText(producto.getNombre());
        txtconcepto.setText(producto.getConcepto()+"- "+producto.getDescripcion());
        txtprecio.setText("$ "+String.valueOf(producto.getPrecio()));
        lbstock.setText("Disponible: "+String.valueOf(producto.getStock()));
        
        btneliminar.setVisible(bandera);//mostramos eliminar
        
        SpinnerNumberModel modelo = new SpinnerNumberModel();
        modelo.setMinimum(0);//valor minimo a seleccionar
        modelo.setMaximum(producto.getStock()); //colocando el valor maximo cuando no estamos editando
        jscantidad.setModel(modelo);//cargando el modelo dentro del seleccionador
       

        if(bandera){//se esta editando
            modelo.setMaximum(producto.getStock()+item.getCantidad()); //colcando el valor maximo cuando estamos editando 
            jscantidad.setValue(item.getCantidad());//seleccionamos el total de items que tiene
        }   
    }
    
    
    public void insertar(int num){
        items=new CRUDItems();
        producto.setStock(producto.getStock() - num); //actualizando el stock
        productos.actualizar(producto); //actualizando en bd
        item=new Item();
        item.setId_pedido(pedido.getId_pedido());
        item.setId_producto(producto.getId_producto());
        item.setCantidad(num);
        item.setMonto(Double.parseDouble(txttotal.getText()));
        items.insertar(item);//Insertando item en bd
    }
    
    public void actualizar(int num){
        productos=new CRUDProductos();
        items=new CRUDItems();
        //se esta editando el item
        //stock=stock-(nuevo-antes)
        producto.setStock(producto.getStock()-(num-item.getCantidad()));//se actualizo el stock
        item.setCantidad(num);//actualizamos la cantidad de datos
        item.setMonto(Double.parseDouble(txttotal.getText()));//actualizando el monto
        
        //Guardamos en la bd
        productos.actualizar(producto);
        items.actualizar(item);
    }
    
    public void eliminar(){
        productos=new CRUDProductos();
        items=new CRUDItems();
        pedidos=new CRUDPedidos();
        //stock=stock+numproductos
        items.eliminar(item.getId_item());//eliminamos el item
        producto.setStock(producto.getStock()+item.getCantidad()); //recuperamos la el stock
        pedido.setCantidadproductos(items.cuentaproductos(pedido.getId_pedido()));//actualizando num productos
        pedido.setTotal(items.sumamonto(pedido.getId_pedido()));    //actualizando total
        
        //actualizando en bd
        pedidos.actualiza(pedido);
        productos.actualizar(producto);
        
    }
    
    

    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtconcepto = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnaceptar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        txtprecio = new javax.swing.JTextField();
        lbstock = new javax.swing.JLabel();
        jscantidad = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Items");

        jLabel1.setText("Producto");

        txtnombre.setEditable(false);

        jLabel2.setText("Concepto");

        txtconcepto.setEditable(false);

        txttotal.setEditable(false);

        jLabel3.setText("Precio");

        jLabel4.setText("Total");

        jLabel5.setText("Cantidad");

        btnaceptar.setBackground(new java.awt.Color(0, 153, 153));
        btnaceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnaceptar.setText("Aceptar");
        btnaceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnaceptarMouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancelar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(255, 102, 102));
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("Eliminar");
        btneliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btneliminarMouseClicked(evt);
            }
        });

        txtprecio.setEditable(false);

        jscantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jscantidadStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btneliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbstock, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtconcepto, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(24, 24, 24))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(9, 9, 9))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(25, 25, 25)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtprecio, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addComponent(txttotal)
                                .addComponent(jscantidad)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(18, 18, 18)
                            .addComponent(btnaceptar))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtconcepto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jscantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbstock, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaceptar)
                    .addComponent(jButton2)
                    .addComponent(btneliminar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // Cancelar
        panel.estado();
        this.dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jscantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jscantidadStateChanged
        double total=0.0;
        int stock,seleccionado,antes=0;
        seleccionado=Integer.parseInt(jscantidad.getValue().toString());//el obtenido por el selector
        stock=producto.getStock();//el stock aun disponible del producto
            
        if(bandera){//cuando se esta editando
        antes=item.getCantidad();
        //stock=stock-(seleccionado-antes)
        stock=stock-(seleccionado-antes);
        }
        total=seleccionado*producto.getPrecio(); //calculando el monto
        lbstock.setText("Disponible: "+stock);
        txttotal.setText(String.valueOf(total));
    }//GEN-LAST:event_jscantidadStateChanged

    private void btnaceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnaceptarMouseClicked
        // Aceptar
        int num = Integer.parseInt(jscantidad.getValue().toString());//obteniendo el numero de productos seleccionados
        pedidos=new CRUDPedidos();

        //verificando una cantidad dentro del rango
        if (num > 0) {
            if (!bandera) {//se esta insertando 
                insertar(num);
            } else {//aqui se actualiza
                actualizar(num);
            }
            pedido.setCantidadproductos(items.cuentaproductos(pedido.getId_pedido()));//actualizando num productos
            pedido.setTotal(items.sumamonto(pedido.getId_pedido()));    //actualizando total
            //actualizando en bd
            pedidos.actualiza(pedido);

            panel.estado();//cargamos el estado
            this.dispose();//salimos
        } else {
            JOptionPane.showMessageDialog(this, "Elija una cantidad correcta");
        }
    }//GEN-LAST:event_btnaceptarMouseClicked

    private void btneliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btneliminarMouseClicked
        // se presiona eliminar
        if (JOptionPane.showConfirmDialog(this, "Se eliminará ¿Desea continuar?",
                "Aviso", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            eliminar();
            panel.estado();
            this.dispose();
        }


    }//GEN-LAST:event_btneliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelItem().setVisible(true);
                
            }
        });

    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaceptar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jscantidad;
    private javax.swing.JLabel lbstock;
    private javax.swing.JTextField txtconcepto;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
